---
- name: Base setup
  command: 'cvmfs_config setup'

- name: Copy files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
    - { template: repository.conf.j2, dest: '/etc/cvmfs/config.d/{{ repository_name }}.conf' }

- name: Copy public key
  copy:
    src: '/tmp/{{ repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ repository_name }}.pub'
    remote_src: true

- name: Restart autofs
  service:
    name: autofs
    state: restarted

# Check configuration

- name: Check config
  command: 'cvmfs_config chksetup'
  register: chksetup_output

- fail:
    msg: 'cvmfs_config chksetup fail!'
  when: chksetup_output.stdout != 'OK'

# Mount cmvfs

- name: Mount filesystem
  command: 'cvmfs_config probe'
  register: probe_output

#sudo mount -t cvmfs elixir-italy.galaxy.refdata /home/galaxy/refdata
# refdata needs to be owned by root!!!

- fail:
    msg: 'cvmfs_config probe fail!'
  when: probe_output.stdout != 'Probing /cvmfs/elixir-italy.galaxy.refdata... OK' 

# Add fstab entry
# lineinfile
#atlas.cern.ch /mnt/test cvmfs defaults,_netdev,nodev 0 0
