---
- name: Base setup
  command: 'cvmfs_config setup'

- name: Copy files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
    - { template: repository.conf.j2, dest: '/etc/cvmfs/config.d/{{ repository_name }}.conf' }

- name: Copy public key
  copy:
    src: '/tmp/{{ repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ repository_name }}.pub'
    remote_src: true

- name: Restart autofs
  service:
    name: autofs
    state: restarted
