---
- name: Base setup
  command: 'cvmfs_config setup'

- name: Copy files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
    - { template: repository.conf.j2, dest: '/etc/cvmfs/config.d/{{ repository_name }}.conf' }

- name: Copy public key
  copy:
    src: '{{ public_key_src_path }}/{{ repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ repository_name }}.pub'
    remote_src: true

- name: Restart autofs
  service:
    name: autofs
    state: restarted

#________________________________
# Check configuration

- name: Check config
  command: 'cvmfs_config chksetup'
  register: chksetup_output

- fail:
    msg: 'cvmfs_config chksetup fail!'
  when: chksetup_output.stdout != 'OK'

#________________________________
# Mount cmvfs

- include: probe.yml
  when: cvmfs_mountpoint == '/cvmfs'

- include: mount.yml
  when: cvmfs_mountpoint != '/cvmfs'

- name: Add fstab entry
  mount:
    path: '{{ cvmfs_mountpoint }}/{{ repository_name }}'
    src: '{{ repository_name }}'
    fstype: cvmfs
    opts: defaults,_netdev,nodev
    state: present
     
# lineinfile
#{{ repository_name }} {{ cvmfs_mountpoint }} cvmfs defaults,_netdev,nodev 0 0
