---
- name: Base setup
  command: 'cvmfs_config setup'

- name: Copy files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
    - { template: repository.conf.j2, dest: '/etc/cvmfs/config.d/{{ repository_name }}.conf' }

- name: Copy public key
  copy:
    src: '{{ public_key_src_path }}/{{ repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ repository_name }}.pub'
    remote_src: true

- name: Restart autofs
  service:
    name: autofs
    state: restarted
  when: ansible_virtualization_type != "docker"
#________________________________
# Check configuration

- name: Check config
  command: 'cvmfs_config chksetup'
  register: chksetup_output

- fail:
    msg: 'cvmfs_config chksetup fail!'
  when: chksetup_output.stdout != 'OK'

#________________________________
# Mount cvmfs

- include: probe.yml
  when: cvmfs_mountpoint == '/cvmfs'

- include: mount.yml
  when: cvmfs_mountpoint != '/cvmfs'
